Initilaising variables...
Traceback (most recent call last):
  File "/home2/mxjf75/othelloML/DeepLearning/WThorParser.py", line 172, in loadTrainingData
    boards_data = np.load(MASTER_PATH + 'boardsData.npy')
UnboundLocalError: local variable 'MASTER_PATH' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./DeepLearning/othelloCNN8.py", line 97, in <module>
    boards_data, moves = WThorParser.loadTrainingData()
  File "/home2/mxjf75/othelloML/DeepLearning/WThorParser.py", line 177, in loadTrainingData
    boards_data = np.load(MASTER_PATH + 'boardsData.npy')
  File "/home2/mxjf75/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './../Data/boardsData.npy'
